### ISSUE TITLE
Are user generated annotations possible?

### ISSUE THREAD

**Issue by rektide** [erights/Orthogonal-Classes#15]
Decorators is listed as [the first of the various syntaxes](https://github.com/erights/Orthogonal-Classes/tree/9cf063e0bcdfa8a3bff2c07099dbd597fade1360#summary) inspiring Orthogonal Classes. The only mention of annotations- which constitutes the core syntax of decorators- comes latter, saying, only that "annotations is defined by the decorators proposal".

Given that decorators are only mentioned obliquely, I'm unclear how this spec intends to relate to decorators. I'm not sure if my title question- "are user generated annotations possible"- makes sense to ask in the context of this spec. How to annotations fit into the Orthogonal Classes specification, and what relationship does this spec see with the existing, currently Stage 2 [Decorators spec](http://tc39.github.io/proposal-decorators/)?

**Comment by ljharb** [comment]
Annotations are one of the things you can do with decorators, so yes, they're possible.
